CREATE DATABASE ELEARNING;
#DROP DATABASE ELEARNING;
USE ELEARNING;

CREATE TABLE INSTITUICAO (
	cnpj VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
	# regions
    PRIMARY KEY (cnpj)
);

CREATE TABLE DEPARTAMENTO (
	cod VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    instituicao VARCHAR(25) NOT NULL,
    PRIMARY KEY (cod),
    FOREIGN KEY (instituicao) REFERENCES INSTITUICAO (cnpj)
);


CREATE TABLE PROFESSOR (
	cod VARCHAR(25) NOT NULL,
    cpf VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    lattes VARCHAR(100) NOT NULL,
    dpto VARCHAR(25) NOT NULL,
    PRIMARY KEY (cod),
    FOREIGN KEY (dpto) REFERENCES DEPARTAMENTO (cod)
);

CREATE TABLE PLATAFORMA (
	cod VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
	link VARCHAR(100) NOT NULL,
    PRIMARY KEY (cod)
);

CREATE TABLE DISCIPLINA (
	cod VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    dpto VARCHAR(25) NOT NULL,
    prof VARCHAR(25) NOT NULL,
	PRIMARY KEY (cod),
    FOREIGN KEY (dpto) REFERENCES DEPARTAMENTO (cod),
    FOREIGN KEY (prof) REFERENCES PROFESSOR (cod)
);

CREATE TABLE ALUNO (
	matricula VARCHAR(25) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(25) NOT NULL,
    nasc DATE NOT NULL,
    PRIMARY KEY (matricula)
);

CREATE TABLE MATRICULAS (
	disciplina VARCHAR(25),
    aluno VARCHAR(25),
    nota INT(3) NOT NULL,
    FOREIGN KEY (disciplina) REFERENCES DISCIPLINA (cod),
    FOREIGN KEY (aluno) REFERENCES ALUNO (matricula)
);

CREATE TABLE MATERIAL_VIDEO (
	cod VARCHAR(25) NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    plataforma VARCHAR(25) NOT NULL,
    link VARCHAR(100) NOT NULL,
    PRIMARY KEY (cod),
    FOREIGN KEY (plataforma) REFERENCES PLATAFORMA (cod)
);

CREATE TABLE TAGS_VIDEO (
	video_id VARCHAR(25) NOT NULL,
    tag VARCHAR(25) NOT NULL,
    FOREIGN KEY (video_id) REFERENCES MATERIAL_VIDEO (cod)
);

CREATE TABLE PALESTRAS (
	cod VARCHAR(25) NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    datahora DATETIME NOT NULL,
    prof VARCHAR(25) NOT NULL,
    video VARCHAR(25) NOT NULL,
    PRIMARY KEY (cod),
	FOREIGN KEY (video) REFERENCES MATERIAL_VIDEO (cod),
    FOREIGN KEY (prof) REFERENCES PROFESSOR (cod)
);

CREATE TABLE INSCRITOS (
	palestra VARCHAR(25) NOT NULL,
    aluno VARCHAR(25) NOT NULL,
    FOREIGN KEY (palestra) REFERENCES PALESTRAS (cod),
    FOREIGN KEY (aluno) REFERENCES ALUNO (matricula)
);

CREATE TABLE ENCONTROS (
	disciplina VARCHAR(25) NOT NULL,
    datahora DATETIME NOT NULL,
    video VARCHAR(25) NOT NULL,
    FOREIGN KEY (disciplina) REFERENCES DISCIPLINA (cod),
    FOREIGN KEY (video) REFERENCES MATERIAL_VIDEO (cod)
);

CREATE TABLE MATERIAL_BIBLIO (
	cod VARCHAR(25) NOT NULL,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    link VARCHAR(100) NOT NULL,
    disciplina VARCHAR(25) NOT NULL,
    FOREIGN KEY (disciplina) REFERENCES DISCIPLINA (cod),# tags
    PRIMARY KEY (cod)
);
